### ISSUE TITLE
Error notification: Left margin on "OK" button

### ISSUE THREAD

**Issue by hauke96** [hauke96/osm-open#18]
The "OK" button in error notifications should have a bit of a margin to the left side:

![image](https://user-images.githubusercontent.com/9700906/143412192-49de7c15-466c-4541-ac3f-ae93032f385e.png)

**Comment by aphive** [comment]
I think I can help with this but I've not created a PR from an issue, if you can help me out with that I can do the PR to add the line you need.

**Comment by aphive** [comment]
PR is [here](https://github.com/hauke96/osm-open/pull/20)
